// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh2q3LC199hse4AfFkP_fOD6WCSAiPP0E',
    appId: '1:712924748990:web:f3438b56defcd6cad512ef',
    messagingSenderId: '712924748990',
    projectId: 'e-commerce-9837a',
    authDomain: 'e-commerce-9837a.firebaseapp.com',
    storageBucket: 'e-commerce-9837a.appspot.com',
    measurementId: 'G-1ZQKYKZHNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcp9VkTRdJFDY9RtER2auVRQwXcKvhI4w',
    appId: '1:712924748990:android:90e84500d7fb3a1cd512ef',
    messagingSenderId: '712924748990',
    projectId: 'e-commerce-9837a',
    storageBucket: 'e-commerce-9837a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz9engTlJtdI-Jqkb9Y1cr5uwMvJSW3rM',
    appId: '1:712924748990:ios:6740660b36f8f9ffd512ef',
    messagingSenderId: '712924748990',
    projectId: 'e-commerce-9837a',
    storageBucket: 'e-commerce-9837a.appspot.com',
    iosBundleId: 'com.example.flutterEcommerce',
  );
}
